<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="improvement">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="goal" type="xs:string"/>
        <xs:element name="steps">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="step" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="risks">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="risk" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
